Repository PrimeDAO/balancer-v2-monorepo, pull requests merged in 2021-11, with the labels that each got.

#24 tokens weight change
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/test/IndexPool.test.ts
Labels: ready for review, reweighing

#25 Feature: Weight adjustment utility
  pkg/pool-weighted/contracts/test/MockIndexPoolUtils.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
Labels: ready for review, re-indexing

#34 Chore: Use InvestmentPool state representation
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/test/IndexPool.test.ts
  pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Labels: ready for review, reweighing

#27 Feature: Weight calculation of uninitialized token (aka price premium)
  pkg/pool-weighted/contracts/test/MockIndexPoolUtils.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
Labels: ready for review, re-indexing

#36 Chore: Add test case
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
Labels: ready for review

#40 Feature-10: State representation for new token
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/contracts/smart/IndexPoolFactory.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/test/IndexPool.test.ts
  pvt/helpers/src/models/pools/weighted/WeightedPool.ts
  pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
  pvt/helpers/src/models/pools/weighted/types.ts
Labels: ready for review, re-indexing

#42 Feature: Make IndexPoolUtils a library
  .github/workflows/ci.yml
  pkg/pool-weighted/contracts/test/MockIndexPoolUtils.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
Labels: ready for review

#50 Chore: Test cases for swap, join, exit
  pkg/pool-weighted/test/IndexPool.test.ts
  pvt/helpers/src/models/tokens/TokenList.ts
Labels: ready for review

#32 Feature: Chore functions only callable by controller
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/contracts/smart/IndexPoolFactory.sol
  pkg/pool-weighted/test/IndexPool.test.ts
  pvt/helpers/src/models/pools/weighted/WeightedPool.ts
  pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Labels: ready for review

#51 Chore: Prevent new (uninitialized) token from being swapped out
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/test/IndexPool.test.ts
Labels: ready for review

#57 Feature: Uninitialized token behavior
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/test/IndexPool.test.ts
  pvt/helpers/src/models/tokens/TokenList.ts
Labels: ready for review

#64 Feature: Token intialization v2
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/contracts/test/MockIndexPoolUtils.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/test/IndexPool.test.ts
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
Labels: ready for review

#66 Chore: Reduce contract size
  pkg/balancer-js/src/utils/errors.ts
  pkg/pool-weighted/contracts/smart/IIndexPool.sol
  pkg/pool-weighted/contracts/smart/IndexPool.sol
  pkg/pool-weighted/contracts/smart/IndexPoolFactory.sol
  pkg/pool-weighted/contracts/utils/IndexPoolUtils.sol
  pkg/pool-weighted/hardhat.config.ts
  pkg/pool-weighted/package.json
  pkg/pool-weighted/test/IndexPool.test.ts
  pkg/solidity-utils/contracts/helpers/BalancerErrors.sol
  pvt/common/setupTests.ts
  pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
  pvt/helpers/src/test/expectEvent.ts
  yarn.lock
Labels: ready for review

#69 Chore: test adding multiple tokens at once to the pool
  pkg/pool-weighted/test/IndexPool.test.ts
  pkg/pool-weighted/test/IndexPoolUtils.test.ts
  pkg/pool-weighted/test/utils/WeightCalculationUtil.test.ts
Labels: ready for review
